FROM node:25-alpine

WORKDIR /app

# Zależności (cache)
COPY package*.json ./
RUN npm install

# Kod będzie montowany z hosta, więc nie kopiujemy src tutaj

EXPOSE 5173

# Vite dev server nasłuchuje na wszystkich interfejsach
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]