# 1. Build stage
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY src ./src
COPY vite.config.js index.html 
COPY public ./public

RUN npm run build

# 2. Serve przez nginx
FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf || true
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
